name: continuous

on: [push]

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Run './build.cmd CompileAndAnalyze'
        run: ./build.cmd CompileAndAnalyze
      - uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: artifacts
          path: artifacts
